[
   {
      "alumno":"Pedro",
      "nota":7.09,
      "ranking":180
   },
   {
      "alumno":"Juan",
      "nota":4,
      "ranking":450
   },
   {
      "alumno":"Sergio",
      "nota":9.5,
      "ranking":23
   },
   {
      "alumno":"Marta",
      "nota":7.75,
      "ranking":145
   },
   {
      "alumno":"Esther",
      "nota":9,
      "ranking":75
   },
   {
      "alumno":"Carlos",
      "nota":6,
      "ranking":200
   },
   {
      "alumno":"Maria",
      "nota":2.5,
      "ranking":475
   },
   {
      "alumno":"Eva",
      "nota":5.2,
      "ranking":320
   },
   {
      "alumno":"Carla",
      "nota":10,
      "ranking":1
   }
]
